"""Add coupon fields to orders table

Revision ID: 8b2b027b30ae
Revises: cf0ebe233c1f
Create Date: 2025-09-20 19:22:15.453476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2b027b30ae'
down_revision: Union[str, Sequence[str], None] = 'cf0ebe233c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('coupon_code', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'discount_amount')
    op.drop_column('orders', 'coupon_code')
    # ### end Alembic commands ###
