"""Update datetime defaults to be timezone-aware

Revision ID: e7b0e3156f87
Revises: 8b2b027b30ae
Create Date: 2025-09-20 19:30:36.592290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b0e3156f87'
down_revision: Union[str, Sequence[str], None] = '8b2b027b30ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
